version: '3.7'
services:
  postgresql:
    image: postgres:13.1-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./var/lib/postgresql/data
    environment:
      - POSTGRES_DB=myhomepc
      - POSTGRES_USER=kirmakin
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
